#!/bin/bash

# This will check the permissions of the files that are considered
# dirty, restoring them if they have changed. This will have no effect
# ona repository which is not considered dirty, so you must clear any
# core.fileMode flag which may conceal such changes.

CHANGES=0
while read permission file
do
    current_permission=$(stat -c "%a" $file)
    if [ "${current_permission}" != "${permission}" ]
    then
        chmod $permission $file
        CHANGES=1
    fi
done < <(git ls-tree -r HEAD | awk ' $2 == "blob" { sub("100", "", $1); print $1 " " $NF } ')

if [ $CHANGES -eq 0 ]
then
    echo "No bad permissions found" >&2
    exit 1
fi
